<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Jenismember extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Jenismember_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'jenismember/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'jenismember/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'jenismember/index.html';
            $config['first_url'] = base_url() . 'jenismember/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Jenismember_model->total_rows($q);
        $jenismember = $this->Jenismember_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'jenismember_data' => $jenismember,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->load->view('jenismember/jenismember_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Jenismember_model->get_by_id($id);
        if ($row) {
            $data = array(
		'idx' => $row->idx,
		'JenisMember' => $row->JenisMember,
	    );
            $this->load->view('jenismember/jenismember_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('jenismember'));
        }
    }

public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('jenismember/create_action'),
	    'idx' => set_value('idx'),
	    'JenisMember' => set_value('JenisMember'),
	);
        $this->load->view('jenismember/jenismember_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'JenisMember' => $this->input->post('JenisMember',TRUE),
	    );

            $this->Jenismember_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('jenismember'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Jenismember_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('jenismember/update_action'),
		'idx' => set_value('idx', $row->idx),
		'JenisMember' => set_value('JenisMember', $row->JenisMember),
	    );
            $this->load->view('jenismember/jenismember_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('jenismember'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('idx', TRUE));
        } else {
            $data = array(
		'JenisMember' => $this->input->post('JenisMember',TRUE),
	    );

            $this->Jenismember_model->update($this->input->post('idx', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('jenismember'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Jenismember_model->get_by_id($id);

        if ($row) {
            $this->Jenismember_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('jenismember'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('jenismember'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('JenisMember', 'jenismember', 'trim|required');

	$this->form_validation->set_rules('idx', 'idx', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Jenismember.php */
/* Location: ./application/controllers/Jenismember.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-02 15:37:10 */
/* http://harviacode.com */