<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Bataswaktu extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Bataswaktu_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'bataswaktu/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'bataswaktu/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'bataswaktu/index.html';
            $config['first_url'] = base_url() . 'bataswaktu/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Bataswaktu_model->total_rows($q);
        $bataswaktu = $this->Bataswaktu_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'bataswaktu_data' => $bataswaktu,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->load->view('bataswaktu/bataswaktu_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Bataswaktu_model->get_by_id($id);
        if ($row) {
            $data = array(
		'idx' => $row->idx,
		'bataswaktu' => $row->bataswaktu,
	    );
            $this->load->view('bataswaktu/bataswaktu_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('bataswaktu'));
        }
    }

public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('bataswaktu/create_action'),
	    'idx' => set_value('idx'),
	    'bataswaktu' => set_value('bataswaktu'),
	);
        $this->load->view('bataswaktu/bataswaktu_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'bataswaktu' => $this->input->post('bataswaktu',TRUE),
	    );

            $this->Bataswaktu_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('bataswaktu'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Bataswaktu_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('bataswaktu/update_action'),
		'idx' => set_value('idx', $row->idx),
		'bataswaktu' => set_value('bataswaktu', $row->bataswaktu),
	    );
            $this->load->view('bataswaktu/bataswaktu_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('bataswaktu'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('idx', TRUE));
        } else {
            $data = array(
		'bataswaktu' => $this->input->post('bataswaktu',TRUE),
	    );

            $this->Bataswaktu_model->update($this->input->post('idx', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('bataswaktu'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Bataswaktu_model->get_by_id($id);

        if ($row) {
            $this->Bataswaktu_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('bataswaktu'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('bataswaktu'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('bataswaktu', 'bataswaktu', 'trim|required');

	$this->form_validation->set_rules('idx', 'idx', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Bataswaktu.php */
/* Location: ./application/controllers/Bataswaktu.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-01 17:35:23 */
/* http://harviacode.com */