<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Marketingproduk_model extends CI_Model
{

    public $table = 'marketingproduk';
    public $id = 'idx';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // GET_LIST_ALLmarketingproduk
    function getListmarketingproduk() {
        $xStr = "SELECT idx,".
 "idmember,".
 "idproduk,".
 "tgldaftar from marketingproduk";
        $query = $this->db->query($xStr);
        
        return $query;
    }

    // GET_Detailmarketingproduk
    function getDetailmarketingproduk($xidx) {
        $xStr = "SELECT idx,".
 "idmember,".
 "idproduk,".
 "tgldaftar from marketingproduk WHERE idx = '". $xidx ."'";
        $query = $this->db->query($xStr);
        $row = $query->row();
        return $row;
    }

    // Insert_marketingproduk
    function Insertmarketingproduk($xidx,$xidmember,$xidproduk,$xtgldaftar) {
        $xStr = " INSERT INTO marketingproduk( idx,".
 "idmember,".
 "idproduk,".
 "tgldaftar ) VALUES ( '" . $xidx
 . "','" .$xidmember
 . "','" .$xidproduk
 . "','" .$xtgldaftar. "')";
        $query = $this->db->query($xStr);
        return $idx; 
    }

    // updatemarketingproduk
    function Updatemarketingproduk($xidx,$xidmember,$xidproduk,$xtgldaftar) {
        $xStr = " UPDATE produk SET ". 
		"idx= '". $xidx . "'," . 
		"idmember= '". $xidmember . "'," . 
		"idproduk= '". $xidproduk . "'," . 
		"tgldaftar= '". $xtgldaftar . "'," . "' WHERE idx = '". $xidx ."'";
 $query = $this->db->query($xStr);
        return $xidx;
    }

    // deletmarketingproduk
    function Deletmarketingproduk($xidx) {
        $xStr = " DELETE FROM marketingproduk WHERE marketingproduk.idx = '" . $xidx . "'";
        $query = $this->db->query($xStr);
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('idx', $q);
	$this->db->or_like('idmember', $q);
	$this->db->or_like('idproduk', $q);
	$this->db->or_like('tgldaftar', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('idx', $q);
	$this->db->or_like('idmember', $q);
	$this->db->or_like('idproduk', $q);
	$this->db->or_like('tgldaftar', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Marketingproduk_model.php */
/* Location: ./application/models/Marketingproduk_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-02 15:37:13 */
/* http://harviacode.com */