<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Member_model extends CI_Model
{

    public $table = 'member';
    public $id = 'id_member';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // GET_LIST_ALLmember
    function getListmember() {
        $xStr = "SELECT nama_member,".
 "alamat_member,".
 "kota,".
 "tglLahir_member,".
 "email_member,".
 "noTelp_member,".
 "id_member from member";
        $query = $this->db->query($xStr);
        
        return $query;
    }

    // GET_Detailmember
    function getDetailmember($xid_member) {
        $xStr = "SELECT nama_member,".
 "alamat_member,".
 "kota,".
 "tglLahir_member,".
 "email_member,".
 "noTelp_member,".
 "id_member from member WHERE id_member = '". $xid_member ."'";
        $query = $this->db->query($xStr);
        $row = $query->row();
        return $row;
    }

    // Insert_member
    function Insertmember($xnama_member,$xalamat_member,$xkota,$xtglLahir_member,$xemail_member,$xnoTelp_member,$xid_member) {
        $xStr = " INSERT INTO member( nama_member,".
 "alamat_member,".
 "kota,".
 "tglLahir_member,".
 "email_member,".
 "noTelp_member,".
 "id_member ) VALUES ( '" . $xnama_member
 . "','" .$xalamat_member
 . "','" .$xkota
 . "','" .$xtglLahir_member
 . "','" .$xemail_member
 . "','" .$xnoTelp_member
 . "','" .$xid_member. "')";
        $query = $this->db->query($xStr);
        return $id_member; 
    }

    // updatemember
    function Updatemember($xnama_member,$xalamat_member,$xkota,$xtglLahir_member,$xemail_member,$xnoTelp_member,$xid_member) {
        $xStr = " UPDATE produk SET ". 
		"nama_member= '". $xnama_member . "'," . 
		"alamat_member= '". $xalamat_member . "'," . 
		"kota= '". $xkota . "'," . 
		"tglLahir_member= '". $xtglLahir_member . "'," . 
		"email_member= '". $xemail_member . "'," . 
		"noTelp_member= '". $xnoTelp_member . "'," . 
		"id_member= '". $xid_member . "'," . "' WHERE id_member = '". $xid_member ."'";
 $query = $this->db->query($xStr);
        return $xid_member;
    }

    // deletmember
    function Deletmember($xid_member) {
        $xStr = " DELETE FROM member WHERE member.id_member = '" . $xid_member . "'";
        $query = $this->db->query($xStr);
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_member', $q);
	$this->db->or_like('nama_member', $q);
	$this->db->or_like('alamat_member', $q);
	$this->db->or_like('kota', $q);
	$this->db->or_like('tglLahir_member', $q);
	$this->db->or_like('email_member', $q);
	$this->db->or_like('noTelp_member', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_member', $q);
	$this->db->or_like('nama_member', $q);
	$this->db->or_like('alamat_member', $q);
	$this->db->or_like('kota', $q);
	$this->db->or_like('tglLahir_member', $q);
	$this->db->or_like('email_member', $q);
	$this->db->or_like('noTelp_member', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Member_model.php */
/* Location: ./application/models/Member_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-03 09:17:32 */
/* http://harviacode.com */