<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Provinsi_model extends CI_Model
{

    public $table = 'provinsi';
    public $id = 'id_provinsi';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // GET_LIST_ALLprovinsi
    function getListprovinsi() {
        $xStr = "SELECT id_provinsi,".
 "nama_provinsi from provinsi";
        $query = $this->db->query($xStr);
        
        return $query;
    }

    // GET_Detailprovinsi
    function getDetailprovinsi($xid_provinsi) {
        $xStr = "SELECT id_provinsi,".
 "nama_provinsi from provinsi WHERE id_provinsi = '". $xid_provinsi ."'";
        $query = $this->db->query($xStr);
        $row = $query->row();
        return $row;
    }

    // Insert_provinsi
    function Insertprovinsi($xid_provinsi,$xnama_provinsi) {
        $xStr = " INSERT INTO provinsi( id_provinsi,".
 "nama_provinsi ) VALUES ( '" . $xid_provinsi
 . "','" .$xnama_provinsi. "')";
        $query = $this->db->query($xStr);
        return $id_provinsi; 
    }

    // updateprovinsi
    function Updateprovinsi($xid_provinsi,$xnama_provinsi) {
        $xStr = " UPDATE produk SET ". 
		"id_provinsi= '". $xid_provinsi . "'," . 
		"nama_provinsi= '". $xnama_provinsi . "'," . "' WHERE id_provinsi = '". $xid_provinsi ."'";
 $query = $this->db->query($xStr);
        return $xid_provinsi;
    }

    // deletprovinsi
    function Deletprovinsi($xid_provinsi) {
        $xStr = " DELETE FROM provinsi WHERE provinsi.id_provinsi = '" . $xid_provinsi . "'";
        $query = $this->db->query($xStr);
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_provinsi', $q);
	$this->db->or_like('nama_provinsi', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_provinsi', $q);
	$this->db->or_like('nama_provinsi', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Provinsi_model.php */
/* Location: ./application/models/Provinsi_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-03 09:17:32 */
/* http://harviacode.com */