<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class User_model extends CI_Model
{

    public $table = 'user';
    public $id = 'id_user';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // GET_LIST_ALLuser
    function getListuser() {
        $xStr = "SELECT id_user,".
 "username,".
 "password from user";
        $query = $this->db->query($xStr);
        
        return $query;
    }

    // GET_Detailuser
    function getDetailuser($xid_user) {
        $xStr = "SELECT id_user,".
 "username,".
 "password from user WHERE id_user = '". $xid_user ."'";
        $query = $this->db->query($xStr);
        $row = $query->row();
        return $row;
    }

    // Insert_user
    function Insertuser($xid_user,$xusername,$xpassword) {
        $xStr = " INSERT INTO user( id_user,".
 "username,".
 "password ) VALUES ( '" . $xid_user
 . "','" .$xusername
 . "','" .$xpassword. "')";
        $query = $this->db->query($xStr);
        return $id_user; 
    }

    // updateuser
    function Updateuser($xid_user,$xusername,$xpassword) {
        $xStr = " UPDATE produk SET ". 
		"id_user= '". $xid_user . "'," . 
		"username= '". $xusername . "'," . 
		"password= '". $xpassword . "'," . "' WHERE id_user = '". $xid_user ."'";
 $query = $this->db->query($xStr);
        return $xid_user;
    }

    // deletuser
    function Deletuser($xid_user) {
        $xStr = " DELETE FROM user WHERE user.id_user = '" . $xid_user . "'";
        $query = $this->db->query($xStr);
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_user', $q);
	$this->db->or_like('username', $q);
	$this->db->or_like('password', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_user', $q);
	$this->db->or_like('username', $q);
	$this->db->or_like('password', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file User_model.php */
/* Location: ./application/models/User_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-03 09:17:32 */
/* http://harviacode.com */